const Index = () => {

    return (
        <>
            <h1>Accueil</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper dignissim massa vel efficitur. Aenean velit tellus, faucibus sit amet nisi sit amet, hendrerit sodales tortor. Nullam id diam et diam posuere facilisis interdum ut velit. Suspendisse et rhoncus tortor. Donec mattis, ligula vitae varius sollicitudin, urna nisi mollis eros, consequat eleifend ante nunc vel justo. Maecenas volutpat dui risus, eu lacinia purus sagittis eu. Phasellus risus massa, suscipit eget rutrum et, dignissim eu ex. Sed vehicula in mauris at elementum. Vivamus commodo, urna et convallis feugiat, erat ipsum lobortis ligula, sit amet tempor velit massa ac nisi. Praesent ex elit, pharetra et lectus auctor, finibus porttitor sapien. Aenean condimentum velit at lorem mattis scelerisque. Quisque vel auctor massa. Mauris porttitor, purus vel euismod tincidunt, libero odio mollis ligula, a malesuada turpis purus at ex
            </p>
        </>
    )
}

export default Index;